SUMMARY = "U-Boot pre-kernel splash asset for the EDGE AI OS platform"
DESCRIPTION = "Deploys splash.bmp into the /boot partition for U-Boot's \
splashload command. The BMP is regenerated by scripts/generate-splash.py \
alongside the psplash PNG so both boot-time surfaces share one source."

LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

inherit deploy

SRC_URI = "file://splash.bmp"
S = "${UNPACKDIR}"

do_compile[noexec] = "1"
do_install[noexec] = "1"

do_deploy() {
    install -d ${DEPLOYDIR}
    install -m 0644 ${UNPACKDIR}/splash.bmp ${DEPLOYDIR}/splash.bmp
}

addtask deploy after do_compile before do_build
